// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/jakepartusch/domain/PersonProto.proto

package com.jakepartusch.domain;

public interface PersonProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string lastName = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
